### ISSUE TITLE
pip completion not working

### ISSUE THREAD

**Issue by simonweil** [ekalinin/pip-bash-completion#3]
When I do this `pip [TAB]` the result is `pip ^[[01;31m^[[K`.

I'm running on on OSX mavrics, bash version 4.2.45.

Tell me if I can help, I'd really like it working.

**Comment by murawskikrzysiek** [comment]
Hi, I am seeing the same issue (in my case it is with ^[[1;35;40m^[[K)
Already have your fix, but does not work for me. Using macOS Sierra
